# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- bash: echo "##vso[task.prependpath]$CONDA/bin"
  displayName: Add conda to PATH

- bash: conda env create -f environment.yml
  displayName: Create conda environment

- bash: |
    source activate computational-representations-message-passing
    make convert
  displayName: Build figures

- bash: |
    source activate computational-representations-message-passing
    make paper
  displayName: Build paper
